### PR TITLE
Web HMI implementation of feature - 0261 New vehicle data WindowStatus

### PR DESCRIPTION
**Pull request by YarikMamykin**
Implements/Fixes [#3193](https://github.com/smartdevicelink/sdl_core/issues/3193)

This PR is **ready** for review.

Testing Plan
Manual testing
Manual checklist: [vehicle_data_windowStatus_instruction.xlsx](https://github.com/smartdevicelink/sdl_hmi/files/4668199/vehicle_data_windowStatus_instruction.xlsx)

Summary
Added WindowStatus to vehicle data type.
Added WindowStatus related data support into Grid-related data.

### CLA
- [X] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Comment by LitvinenkoIra** [comment]
@atiwari9 please review this PR

**Comment by atiwari9** [comment]
PR Approved.

**Comment by LitvinenkoIra** [comment]
@theresalech PR is ready for Livio review. Thank you!

**Comment by theresalech** [comment]
Resolves #267

**Comment by ShobhitAd** [comment]
All feature PRs have been approved. Please resolve merge conflicts

**Comment by AKalinich-Luxoft** [comment]
> All `WindowStatus` feature PRs have been approved. Please resolve the merge conflicts

@ShobhitAd conflicts have been resolved

**Pull request merged**
