### PR TITLE
Add support of CustomerConectivitySettings(CCS)

### PR DESCRIPTION
**Pull request by LevchenkoS**
- Removed privacy mode from model and appPermissionsView
- Added moving to appPermissionsView state with clicking
  to item in appPermissionsListView
- Added default CCS to model (CCS will be added to
  appPermissionsView by default)
- Added processing of CCS from incomming message
- Added sending CCS to SDL
##
@LuxoftAKutsan, @VVeremjova, @okozlovlux, please, review.

### CODE REVIEW

**Comment by LuxoftAKutsan** [comment]
@LevchenkoS I am no sure that is should be on develop branch

**Comment by okozlovlux** [comment]
@LevchenkoS , `CCS` should be name `ExternalConsent`

**Comment by okozlovlux** [comment]
@LevchenkoS ,  think  `CCS` should be named `ExternalConsent`

**Comment by LuxoftAKutsan** [comment]
Target branch https://github.com/smartdevicelink/sdl_hmi/tree/feature/extended_policy_functionality

**Pull request closed without merging**
