### PR TITLE
Web HMI implementation of feature - 0257 New vehicle data HandsOffSteering

### PR DESCRIPTION
**Pull request by YarikMamykin**
Implements/Fixes [#3126](https://github.com/smartdevicelink/sdl_core/issues/3126)

This PR is **ready** for review.

### Testing Plan
Manual testing
Manual checklist: [vehicle_data_handsOffSteering_instruction.xlsx](https://github.com/smartdevicelink/sdl_hmi/files/4668890/vehicle_data_handsOffSteering_instruction.xlsx)

### Summary
Added new handsOffSteering data type.

### CLA
- [X] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Comment by LitvinenkoIra** [comment]
@atiwari9 please review this PR

**Comment by atiwari9** [comment]
PR Approved.

**Comment by LitvinenkoIra** [comment]
@theresalech PR is ready for Livio review. Thank you!

**Comment by theresalech** [comment]
Resolves #262

**Pull request merged**
