### PR TITLE
Web HMI implementation for feature - 0266 New vehicle data gearStatus

### PR DESCRIPTION
**Pull request by mkorniichuk**
Implements [#3216](https://github.com/smartdevicelink/sdl_core/issues/3216)

This PR is **ready** for review.

### Testing Plan
Manual testing.
Manual checklist: [vehicle_data_GearStatus_instruction.xlsx](https://github.com/smartdevicelink/sdl_hmi/files/4695568/vehicle_data_GearStatus_instruction.xlsx)

### Summary
Current PR contains new vehicle data type: gearStatus.

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Comment by LitvinenkoIra** [comment]
@atiwari9 please review this PR

**Comment by atiwari9** [comment]
PR Approved.

**Comment by LitvinenkoIra** [comment]
@theresalech PR is ready for Livio review. Thank you!

**Comment by theresalech** [comment]
Resolves #273

**Pull request merged**
