### PR TITLE
Fix responses sequence for Alert and SubtleAlert

### LINKED ISSUE #465: HMI sends UI.Alert response earlier than TTS.Alert during processing two Alert requests
**Description:**
HMI sends UI.Alert response earlier than TTS.Alert during processing two Alert requests
Note:  Issue is applicable for Alert and SubtleAlert RPCs

**Occurrence:**  100%

**Preconditions:** 
1.   Start WebHMI and SDL
2.   Connect mobile device and consent it
3.   Register app from mobile device
4.   Activate the app

**Steps to reproduce:**
1. Send SubtleAlert request from the app
2. Send another SubtleAlert request from the app during the duration of displaying of SubtleAlert RPC from the previous step

**Expected result:**
HMI responds with code 4 to requests related to the second SubtleAlert request,
HMI send response to UI part only after sending response to TTS part
HMI -> SDL: {"error":{"code":4,"message":"TTS in progress. Rejected.","data":{"method":"TTS.Speak"}}}
HMI -> SDL: {"error":{"code":4,"message":"another SubtleAlert is active","data":{"method":"UI.SubtleAlert"}}}

Observed behavior:
HMI sends UI.Alert response earlier than TTS.Alert during processing two Alert requests
HMI -> SDL: {"error":{"code":4,"message":"another SubtleAlert is active","data":{"method":"UI.SubtleAlert"}}}
HMI -> SDL: {"error":{"code":4,"message":"TTS in progress. Rejected.","data":{"method":"TTS.Speak"}}}

**Environment:**
HMI: https://github.com/smartdevicelink/sdl_hmi/tree/develop (3bbcd28)
SDL: https://github.com/LuxoftSDL/sdl_core (7af6696)
Mobile App: SPT 20201023

### PR DESCRIPTION
**Pull request by AKalinich-Luxoft**
Fixes #465 

This PR is **ready** for review.

### Testing Plan
Covered by manual test plan

### Summary
There was noticed an issue [#3563](https://github.com/smartdevicelink/sdl_core/issues/3563) when SDL sends unexpected `TTS.StopSpeaking` request to HMI. This is a correct SDL behavior according to requirements for case when SDL receives response on UI part of `Alert`/`SubtleAlert` BEFORE receiving response on `TTS.Speak` part of request. HMI has been implemented in a way to send responses on UI part right away after receiving, so this sequence triggers SDL to stop TTS from it's side explicitly, however corresponding speak request was even not started yet.
To fix that sequence, added logic to postpone responses for `UI.Alert` and `UI.SubtleAlert` if TTS part is expected from SDL. In that case, if by some reason request is being rejected and TTS part is expected, HMI will register `TTS.Speak` listener and send response to UI part only after sending response to TTS part. In that case SDL will not send redundant `TTS.StopSpeaking` request to HMI.
**Note** TTS part of request for `Alert`/`SubtleAlert` can be predicted by HMI by `alertType` parameter of UI part. However, there is no way to predict the same for `AlertManeuver` and `PerformAPT` RPCs. Probably, this is a good candidate for a new proposal.

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Review by Ypostolov — APPROVED** [review]

**Comment by jordynmackool** [comment]
@AKalinich-Luxoft I noticed there is an approval on the PR from the Luxoft team. Is this PR ready for Livio review?

**Comment by KhrystynaDubovyk** [comment]
@jordynmackool, currently the PR is not ready for Livio review. 
We will let you know as soon as it is ready.

**Comment by AKalinich-Luxoft** [comment]
@jordynmackool all conflicts have been resolved and PR is ready for Livio review

**Comment by JackLivio** [comment]
@AKalinich-Luxoft Does this fix mean that https://github.com/smartdevicelink/sdl_core/issues/3563 can be closed?

**Comment by AKalinich-Luxoft** [comment]
> @AKalinich-Luxoft Does this fix mean that [smartdevicelink/sdl_core#3563](https://github.com/smartdevicelink/sdl_core/issues/3563) can be closed?

@JackLivio yes, SDL issue can be closed as its behavior is correct in this case

**Review by JackLivio — APPROVED** [review]

**Pull request merged**
