### PR TITLE
Fixed issue: HMI does not reject Navi.AlertManeuver request in case another AlertManeuver request is in progress

### PR DESCRIPTION
**Pull request by ValeriiMalkov**
Fixes [#619](https://github.com/smartdevicelink/sdl_hmi/issues/619)

This PR is **ready** for review.

### Testing Plan
Manual testing

### Summary
Added check AlertManeuver is active

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Comment by ValeriiMalkov** [comment]
Hi @theresalech ! This is a regression issue and ready for livio team review!

**Comment by JackLivio** [comment]
Thank you for submitting this issue. Upon further review it appears that this issue currently exists on master, and is therefore not a regression issue (one that was introduced in 5.6 development). As we are now finalizing our testing of SDL HMI 5.6, we are only focusing on regression issues. We will review this PR when time allows after the 5.6 release.

**Comment by GetmanetsIrina** [comment]
@JackLivio , HMI has a little different behaviour on master branch.
On master branch, HMI does not respond to the one of Navigation.AlertManeuver requests,
but on release/5.6.0 branch HMI responds with invalid id=0, so we trit such issue as regression one and propose the general fix for rejecting of the second request.

**Comment by JackLivio** [comment]
@GetmanetsIrina 

We would consider fixing this issue this late in the release cycle if the functionality was working properly on master and was broken at some point during development. Because there is still an issue on master we will not be able to consider the fix for this release.

I verified the difference in behavior on both versions and mobile still receives the same set of messages therefore we are considering the impact to be low.

**Review by iCollin — APPROVED** [review]

**Pull request merged**
