### PR TITLE
Feature/Remote Control - Radio and Climate Parameter Update

### PR DESCRIPTION
**Pull request by LuxoftAKutsan**
Fixes : https://github.com/smartdevicelink/sdl_core/issues/2793 
This PR is **ready** for review.

### Summary
This proposal changes the minimum index of HD radio sub-channels from 1 to 0.
In addition, we propose to add a new parameter climateEnable to ClimateControlData which will allow an application to power climate control on or off.

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Comment by JackLivio** [comment]
Got this error in controller.js
```
Uncaught TypeError: Cannot read property 'set' of null
    at d.onSubMenu (Controller.js:133)
```

```
     */
    onSubMenu: function(id) {
      this.model.set('currentSubMenuId', id);
    },
```

**Comment by ValeriiMalkov** [comment]
@JackLivio Defect was found during implementation of other feature. But an implementation currently in progress. Can the fix will be provide with an other feature or would you like to see fix in this PR ?

**Comment by JackLivio** [comment]
@ValeriiMalkov Thank you for the note. No that is ok, the fix does not need to be in this pr if this pr is not the origin of the issue.

**Comment by ValeriiMalkov** [comment]
@JackLivio You are welcome. No, this PR is not the origin of the issue.

**Comment by JackLivio** [comment]
The issue is caused by sending a buttonPress "SOURCE" for Radio module. It is duplicated on develop. I will create a separate issue.

**Comment by theresalech** [comment]
Resolves issue #193

**Pull request merged**
