### PR TITLE
Feature/sdl 0293 oem exclusive apps support

### PR DESCRIPTION
**Pull request by LitvinenkoIra**
Implements 0293 initial proposal https://github.com/smartdevicelink/sdl_core/issues/3599

This PR is **ready** for review.

### Testing Plan
Tested manually

**Note:**  [Manual_instruction_for_Enable_OEM_exclusive_apps_support_v3.0.zip](https://github.com/smartdevicelink/sdl_hmi/files/5916814/Manual_instruction_for_Enable_OEM_exclusive_apps_support_v3.0.zip)

### Summary
- Renamed CCPU editor to versions editor
- Added possibility to edit vehicle type structure and optional fields sending
- Added possibility to edit system hardware version and enable/disable its sending in response

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Comment by ashwink11** [comment]
@jordynmackool this PR is ready for review and is approved by Ford.

**Comment by jordynmackool** [comment]
@LitvinenkoIra the proposal markdown file has been updated per the revisions included in the accepted with revisions review issue: [SDL 0293 Revisions - Enable OEM exclusive apps support](https://github.com/smartdevicelink/sdl_evolution/issues/1108). 

Please make the needed updates to this PR and then tag @JackLivio to review when ready. Thanks!

**Comment by AKalinich-Luxoft** [comment]
@JackLivio this PR has been updated according to latest revisions and ready for review

**Comment by JackLivio** [comment]
FYI the file zip in the pr description says keyboard enhancements. The test instructions are for this pr, the file name just needs updating.

**Comment by AKalinich-Luxoft** [comment]
> FYI the file zip in the pr description says keyboard enhancements. The test instructions are for this pr, the file name just needs updating.

@JackLivio thank you. PR description has been updated

**Review by JackLivio — APPROVED** [review]

**Pull request merged**
