### PR TITLE
Add new structure ClimateData into VehicleData

### PR DESCRIPTION
**Pull request by LitvinenkoIra**
Implements https://github.com/smartdevicelink/sdl_hmi/issues/270

This PR is **[ready]** for review.

### Testing Plan
Manual testing 
[New_vehicle_data_climateData_instruction.xlsx](https://github.com/smartdevicelink/sdl_hmi/files/5602986/New_vehicle_data_climateData_instruction.xlsx)

### Summary
Add new vehicle data ClimateData

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Comment by KhrystynaDubovyk** [comment]
@atiwari9 please review this PR

**Review by atiwari9 — APPROVED** [review]

**Comment by LitvinenkoIra** [comment]
@JackLivio This PR is ready for Livio review. Thank you!

**Review by ShobhitAd — APPROVED** [review]

**Comment by ShobhitAd** [comment]
@LitvinenkoIra Please resolve merge conflicts

**Comment by AKalinich-Luxoft** [comment]
> @LitvinenkoIra Please resolve merge conflicts

@ShobhitAd resolved in https://github.com/smartdevicelink/sdl_hmi/pull/468/commits/90e6842abcfa0d9c4d7e989625a916fa906a0d9e

**Pull request merged**
